targets:
  $default:
    builders:
      design_by_contract|contract_builder:
        generate_for:
          include:
            - lib/**/*.dart

builders:
  contract_builder:
    import: "package:design_by_contract/design_by_contract.dart"
    builder_factories: ["contractBuilder"]
    build_extensions: {".dart": [".contract.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]