name: design_by_contract
description: A Dart library for implementing Design by Contract (DbC) using annotations and code generation.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer:
  source_gen: ^1.3.2
  build: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
